language: php

php:
  - 7.2
  - 7.3
  - 7.4

install:
  - composer self-update
  - composer global require "fxp/composer-asset-plugin:^1.3"
  - composer install

before_script:
  - travis_retry composer self-update
  - travis_retry composer install --no-interaction --prefer-source --dev

script:
    - php vendor/bin/phpunit -c phpunit.xml.dist
    - php vendor/bin/php-cs-fixer fix src

branches:
  only: master

cache:
  directories:
  - vendor
  - $HOME/.cache/composer
