<?php

namespace app\components;

use Yii;
use yii\base\Component;

/**
 * @property $opengraph \app\components\OpenGraph
 * @property OpenGraph title($name)
*/
class OpenGraph extends Component
{
    /**
     * Metadata basic
     *
     * @var array
    */
    private static $_metadata = [
        'title',
        'type',
        'image',
        'url',
        'description',
        'audio',
        'locale',
        'site_name',
        'video',
    ];

    /**
     * @param string $name
     * @param array $params
     * @return mixed
     */
    public function __call($name, $params)
    {
        if(in_array($name, self::$_metadata)) {
            $this->registerOpenGraph($name, array_shift($params));
        } else {
            return parent::__call($name, $params); // TODO: Change the autogenerated stub
        }
    }


    /**
     * Register new element of open graph
     *
     * @param string $property Property for metadata
     * @param string $content Content for metadata
     * @throws \InvalidArgumentException
    */
    protected function registerOpenGraph(string $property, string $content)
    {
        Yii::$app->view->registerMetaTag([
            'property' => 'og:' . $property,
            'content'  => $content
        ]);
    }

}